rwcancel/fdset.go, rwcancel/rwcancel.go, rwcancel/rwcancel_windows.go, rwcancel/select_default.go
This lets us include the package on those platforms in a
followup commit where we split out a conn package from device.
It also lets us run `go test ./...` when developing on macOS.
Signed-off-by: David Crawshaw <crawshaw@tailscale.com>
=> rwcancel: no-op builds for windows and darwin

device/peer.go, device/peer_test.go
All atomic access must be aligned to 64 bits, even on 32-bit
platforms. Go promises that the start of allocated structs is
aligned to 64 bits. So, place the atomically-accessed things
first in the struct so that they benefit from that alignment.
As a side bonus, it cleanly separates fields that are accessed
by atomic ops, and those that should be accessed under mu.
Also adds a test that will fail consistently on 32-bit platforms
if the struct ever changes again to violate the rules. This is
likely not needed because unaligned access crashes reliably,
but this will reliably fail even if tests accidentally pass due
to lucky alignment.
Signed-Off-By: David Anderson <dave@natulte.net>
=> Make device.Peer safe for atomic access on 32-bit.

main_windows.go, wgcfg/ip.go, wgcfg/ip_test.go
Before:
```text
$ go test -benchmem -bench=BenchmarkCIDRContains -benchtime=10s ./wgcfg
goos: windows
goarch: amd64
pkg: github.com/tailscale/wireguard-go/wgcfg
BenchmarkCIDRContainsIPv4/IPv4-8                138954278               85.2 ns/op            52 B/op          2 allocs/op
BenchmarkCIDRContainsIPv4/IPv6-8                100000000              102 ns/op              64 B/op          2 allocs/op
PASS
ok      github.com/tailscale/wireguard-go/wgcfg 31.010s
```
After:
```
$ go test -benchmem -bench=BenchmarkCIDRContains -benchtime=10s ./wgcfg
goos: windows
goarch: amd64
pkg: github.com/tailscale/wireguard-go/wgcfg
BenchmarkCIDRContainsIPv4/IPv4-8                1000000000              11.7 ns/op             0 B/op          0 allocs/op
BenchmarkCIDRContainsIPv4/IPv6-8 …
```
=> Add fast CIDR.Contains implementation

device/config.go, wgcfg/ip.go
During incremental reconfig, we iterate over a list of wgcfg.CIDR.
This makes the loop variable contain IP bytes that get clobbered on
every loop iteration. We then passed a slice of those IP bytes into
the trie for storage. So, any time we iterated through the loop more
than once (i.e. any node advertising subnet routes), we corrupted
the allowedips trie.
Signed-off-by: David Anderson <danderson@tailscale.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/wireguard-go/11)
=> device: fix trie corruption during incremental reconfiguration.

wgcfg/writer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/wireguard-go/13)
=> wgcfg: fix bug preventing IPv6 addresses from working

device/device.go, device/device_test.go, device/receive.go, device/send.go
This is the other leg of tailscale/tailscale#358 (and, as such, should be merged after it). This change brings us closer to upstream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/wireguard-go/15)
=> device/device: remove packet filtering.

device/config.go, device/config_test.go, device/send.go
This is the Wireguard half of the changes necessary to eliminate races in `ipn/e2e_test.go`.
Updates tailscale/corp#255.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/wireguard-go/16)
=> device: fix locking in config and send

device/device.go
Peers are currently removed after Device's goroutines are signaled to stop, but without waiting for them to actually do so, which is racy.
For example, RoutineHandshake may be in Peer.SendKeepalive when the corresponding peer is removed, which closes its nonce channel. This causes a send on a closed channel, as observed in tailscale/tailscale#487.
This patch seems to be the correct synchronizing action: Peer's goroutines are receivers and handle channel closure gracefully, so Device's goroutines are the ones that should be fully stopped first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/wireguard-go/18)
=> device: wait for routines to stop before removing peers

device/device.go, device/send.go, device/uapi.go
Both changes enable preventing calls to AllowedIPs.EntriesForPeer when
unneeded.
We've found AllowedIPs to be a hot path.
Signed-off-by: Brad Fitzpatrick <brad@danga.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/wireguard-go/19)
=> device: add Device.IpcGetOperationFiltered and change HandshakeDone callback

device/config.go, device/peer.go
Usually, a peer's AllowedIPs don't change during reconfig, so no need to
call AllowedIPs.RemoveByPeer (which is very expensive currently; see
https://github.com/WireGuard/wireguard-go/pull/36).
Instead, remember what it was previously.
Also, one unrelated minor optimization to reduce some map garbage
during reconfig when endpoints don't change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/wireguard-go/20)
=> device: avoid unnecessary AllowedIPs.RemoveByPeer calls during Reconfig

conn/conn.go, conn/conn_default.go, conn/conn_linux.go, device/config.go, device/config_test.go, wgcfg/config.go, wgcfg/parser.go, wgcfg/parser_test.go, wgcfg/writer.go
This is less type safe, but it eliminates another
widely used wgcfg type. There's no good place to put
the Endpoint type as we migrate code across modules.
After this, the only remaining wgcfg types used
in this module are in device/config{_test}.go.
=> all: convert []wgcfg.Endpoint to a string

conn/conn.go, conn/conn_default.go, conn/conn_linux.go, device/allowedips.go, device/peer.go, device/receive.go, device/send.go
This is a revert of three commits in our fork:
Revert "device: do not call UpdateDst on nil endpoints"
This reverts commit eb5cf120e378cd96ae97d6034af4330176173613.
Revert "[HACK] peer: Don't allow UpdateDst() to an endpoint in our list of routes."
This reverts commit 5064d11a19742bdbf8cb299aa9d5447af64d38f7.
Revert "[Tailscale] device: pass around *net.UDPAddr in addition to Endpoint."
This reverts commit 9e373c18044cdf0fad400e890948c4e274816cbc.
=> device: revert UpdateDst callback and related code

.github/workflows/linux.yml, .github/workflows/linux32.yml, .github/workflows/windows.yml, tun/wintun/memmod/memmod_windows.go
This change adds Github Actions to run tests on Linux and Windows.
Both normal and race-enabled tests.
Fixes tailscale/tailscale#913
Signed-off-by: Alex Brainman <alex.brainman@gmail.com>
=> .github/workflows: run tests on Linux and Windows

device/config.go, device/config_test.go, wgcfg/writer.go
Once this is in, we should be able to move device/config{_test}.go
and package wgcfg to the Tailscale repo.
Thanks to Adrian, who paired with me in getting this completed.
=> device: rewrite Reconfig to use UAPI

device/device.go, device/device_test.go, main.go, main_windows.go
And make DeviceOptions optional.
And assume that DeviceOptions are all-or-none.
And remove an unnecessary argument from CreateBind.
These change reduces merge pain by making call sites
look more like upstream call sites, and by removing
unnecessary complexity.
=> device: move Logger out of DeviceOptions

device/sticky_linux.go
Workaround to support Cloud Run, which has no AF_NETLINK
RTMGRP support.
Signed-off-by: Denton Gentry <dgentry@tailscale.com>
=> device: disable route listener.

device/device.go, device/uapi.go
When opts are set, concatenate the public key and the addrs.
Making the function signature of DeviceOptions.createEndpoint match
that of conn.CreateEndpoint makes merges with upstream easier.
This is ugly, but it is also temporary.
I plan to embed the public key in the addr in a more principled
way in the future on the Tailscale side.
This just unblocks me while I work on other aspects
of merging and fork removal.
While we're here, make skipBindUpdate implicit as well.
=> device: make CreateEndpoint have only one param

conn/bind_windows.go, tun/tun_freebsd.go, tun/tun_windows.go, version.go
Pull in a few minor commits from upstream.
The primary one of interest is the last,
which fixes races when closing a TUN device on windows.
- tun: freebsd: restructure and cleanup
- tun: freebsd: become controlling process when reopening tun FD
- tun: freebsd: avoid OOB writes
- version: bump snapshot
- conn: windows: do not error out when receiving UDP jumbogram
- tun: windows: protect reads from closing
=> merge from upstream

device/receive.go
I've sent this patch upstream, but it hasn't been reviewed yet.
Since we want it for 1.18, apply locally here and fix up as needed
during the 1.10 cycle during the next merge from upstream.
=> device: log all errors received by RoutineReceiveIncoming

device/device.go, device/uapi.go
Depends on https://github.com/tailscale/tailscale/pull/1913 being merged.
=> device: delete device options

device/device.go
I traced the code and did not see a way that this could be set to zero. However, the relevant code paths cross network boundaries and meander into a great many places, so I am slightly nervous I may have missed something.
=> device: remove option to set private_key to zero
